name: Process new comment on issue

on: 
  pull_request: # TODO change with issue_comment

jobs:
  wti:
    name: Run wti
    runs-on: windows-2022
    permissions:
      issues: write
    steps: 
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - uses: ./.github/actions/triage
          with: 
              issue: '11306'
              comment: '2010845646'