name: Sync GitHub with ADO

on: 
  pull_request:

jobs:
  wti:
    name: Run wti
    runs-on: windows-2022
    permissions:
      issues: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: 'Run WTI'
        run: cd .github\workflows && .\wti.exe --issue 11307 --config config.yml --github-token "${{ secrets.GITHUB_TOKEN }}" --ignore-tags
