name: Sync GitHub with ADO

on: 
  pull_request:

jobs:
  getSimilarIssues:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.getBody.outputs.message }}
    steps:
      - uses: actions/checkout@v2
      - id: getBody
        uses: craigloewen-msft/GitGudSimilarIssues@main
        with:
          issueTitle: "Cannot install WSL on latest Windows Insider dev build" # Hardcoded for testing
          issueBody: "Cannot install WSL on latest Windows Insider dev build" # Hardcoded for testing
          repository: ${{ github.repository }}
          similarityTolerance: "0.1" # Lowered value for testing

  wti:
    name: Run wti
    needs: getSimilarIssues
    runs-on: windows-2022
    permissions:
      issues: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: 'Run WTI'
        if: ${{ !contains(needs.getSimilarIssues.outputs.message, '''@') }} # Skip this step if the description contains a string that will break the here document
        run: |
            cd echo @'
            ${{ needs.getSimilarIssues.outputs.message }}
            '@ |  .github\workflows && .\wti.exe --issue 11305 --config config.yml --github-token "${{ secrets.GITHUB_TOKEN }}" --ignore-tags --default-message-stdin